export const countries = [
  { code: 'AF', label: 'Afghanistan', emoji: '🇦🇫' },
  { code: 'AL', label: 'Albania', emoji: '🇦🇱' },
  { code: 'DZ', label: 'Algeria', emoji: '🇩🇿' },
  { code: 'AD', label: 'Andorra', emoji: '🇦🇩' },
  { code: 'AO', label: 'Angola', emoji: '🇦🇴' },
  { code: 'AG', label: 'Antigua and Barbuda', emoji: '🇦🇬' },
  { code: 'AR', label: 'Argentina', emoji: '🇦🇷' },
  { code: 'AM', label: 'Armenia', emoji: '🇦🇲' },
  { code: 'AU', label: 'Australia', emoji: '🇦🇺' },
  { code: 'AT', label: 'Austria', emoji: '🇦🇹' },
  { code: 'AZ', label: 'Azerbaijan', emoji: '🇦🇿' },
  { code: 'BS', label: 'Bahamas', emoji: '🇧🇸' },
  { code: 'BH', label: 'Bahrain', emoji: '🇧🇭' },
  { code: 'BD', label: 'Bangladesh', emoji: '🇧🇩' },
  { code: 'BB', label: 'Barbados', emoji: '🇧🇧' },
  { code: 'BY', label: 'Belarus', emoji: '🇧🇾' },
  { code: 'BE', label: 'Belgium', emoji: '🇧🇪' },
  { code: 'BZ', label: 'Belize', emoji: '🇧🇿' },
  { code: 'BJ', label: 'Benin', emoji: '🇧🇯' },
  { code: 'BT', label: 'Bhutan', emoji: '🇧🇹' },
  { code: 'BO', label: 'Bolivia', emoji: '🇧🇴' },
  { code: 'BA', label: 'Bosnia and Herzegovina', emoji: '🇧🇦' },
  { code: 'BW', label: 'Botswana', emoji: '🇧🇼' },
  { code: 'BR', label: 'Brazil', emoji: '🇧🇷' },
  { code: 'BN', label: 'Brunei', emoji: '🇧🇳' },
  { code: 'BG', label: 'Bulgaria', emoji: '🇧🇬' },
  { code: 'BF', label: 'Burkina Faso', emoji: '🇧🇫' },
  { code: 'BI', label: 'Burundi', emoji: '🇧🇮' },
  { code: 'CV', label: 'Cabo Verde', emoji: '🇨🇻' },
  { code: 'KH', label: 'Cambodia', emoji: '🇰🇭' },
  { code: 'CM', label: 'Cameroon', emoji: '🇨🇲' },
  { code: 'CA', label: 'Canada', emoji: '🇨🇦' },
  { code: 'CF', label: 'Central African Republic', emoji: '🇨🇫' },
  { code: 'TD', label: 'Chad', emoji: '🇹🇩' },
  { code: 'CL', label: 'Chile', emoji: '🇨🇱' },
  { code: 'CN', label: 'China', emoji: '🇨🇳' },
  { code: 'CO', label: 'Colombia', emoji: '🇨🇴' },
  { code: 'KM', label: 'Comoros', emoji: '🇰🇲' },
  { code: 'CG', label: 'Congo', emoji: '🇨🇬' },
  { code: 'CR', label: 'Costa Rica', emoji: '🇨🇷' },
  { code: 'HR', label: 'Croatia', emoji: '🇭🇷' },
  { code: 'CU', label: 'Cuba', emoji: '🇨🇺' },
  { code: 'CY', label: 'Cyprus', emoji: '🇨🇾' },
  { code: 'CZ', label: 'Czechia', emoji: '🇨🇿' },
  { code: 'DK', label: 'Denmark', emoji: '🇩🇰' },
  { code: 'DJ', label: 'Djibouti', emoji: '🇩🇯' },
  { code: 'DM', label: 'Dominica', emoji: '🇩🇲' },
  { code: 'DO', label: 'Dominican Republic', emoji: '🇩🇴' },
  { code: 'EC', label: 'Ecuador', emoji: '🇪🇨' },
  { code: 'EG', label: 'Egypt', emoji: '🇪🇬' },
  { code: 'SV', label: 'El Salvador', emoji: '🇸🇻' },
  { code: 'GQ', label: 'Equatorial Guinea', emoji: '🇬🇶' },
  { code: 'ER', label: 'Eritrea', emoji: '🇪🇷' },
  { code: 'EE', label: 'Estonia', emoji: '🇪🇪' },
  { code: 'SZ', label: 'Eswatini', emoji: '🇸🇿' },
  { code: 'ET', label: 'Ethiopia', emoji: '🇪🇹' },
  { code: 'FJ', label: 'Fiji', emoji: '🇫🇯' },
  { code: 'FI', label: 'Finland', emoji: '🇫🇮' },
  { code: 'FR', label: 'France', emoji: '🇫🇷' },
  { code: 'GA', label: 'Gabon', emoji: '🇬🇦' },
  { code: 'GM', label: 'Gambia', emoji: '🇬🇲' },
  { code: 'GE', label: 'Georgia', emoji: '🇬🇪' },
  { code: 'DE', label: 'Germany', emoji: '🇩🇪' },
  { code: 'GH', label: 'Ghana', emoji: '🇬🇭' },
  { code: 'GR', label: 'Greece', emoji: '🇬🇷' },
  { code: 'GD', label: 'Grenada', emoji: '🇬🇩' },
  { code: 'GT', label: 'Guatemala', emoji: '🇬🇹' },
  { code: 'GN', label: 'Guinea', emoji: '🇬🇳' },
  { code: 'GW', label: 'Guinea-Bissau', emoji: '🇬🇼' },
  { code: 'GY', label: 'Guyana', emoji: '🇬🇾' },
  { code: 'HT', label: 'Haiti', emoji: '🇭🇹' },
  { code: 'HN', label: 'Honduras', emoji: '🇭🇳' },
  { code: 'HU', label: 'Hungary', emoji: '🇭🇺' },
  { code: 'IS', label: 'Iceland', emoji: '🇮🇸' },
  { code: 'IN', label: 'India', emoji: '🇮🇳' },
  { code: 'ID', label: 'Indonesia', emoji: '🇮🇩' },
  { code: 'IR', label: 'Iran', emoji: '🇮🇷' },
  { code: 'IQ', label: 'Iraq', emoji: '🇮🇶' },
  { code: 'IE', label: 'Ireland', emoji: '🇮🇪' },
  { code: 'IL', label: 'Israel', emoji: '🇮🇱' },
  { code: 'IT', label: 'Italy', emoji: '🇮🇹' },
  { code: 'JM', label: 'Jamaica', emoji: '🇯🇲' },
  { code: 'JP', label: 'Japan', emoji: '🇯🇵' },
  { code: 'JO', label: 'Jordan', emoji: '🇯🇴' },
  { code: 'KZ', label: 'Kazakhstan', emoji: '🇰🇿' },
  { code: 'KE', label: 'Kenya', emoji: '🇰🇪' },
  { code: 'KI', label: 'Kiribati', emoji: '🇰🇮' },
  { code: 'KP', label: 'North Korea', emoji: '🇰🇵' },
  { code: 'KR', label: 'South Korea', emoji: '🇰🇷' },
  { code: 'KW', label: 'Kuwait', emoji: '🇰🇼' },
  { code: 'KG', label: 'Kyrgyzstan', emoji: '🇰🇬' },
  { code: 'LA', label: 'Laos', emoji: '🇱🇦' },
  { code: 'LV', label: 'Latvia', emoji: '🇱🇻' },
  { code: 'LB', label: 'Lebanon', emoji: '🇱🇧' },
  { code: 'LS', label: 'Lesotho', emoji: '🇱🇸' },
  { code: 'LR', label: 'Liberia', emoji: '🇱🇷' },
  { code: 'LY', label: 'Libya', emoji: '🇱🇾' },
  { code: 'LI', label: 'Liechtenstein', emoji: '🇱🇮' },
  { code: 'LT', label: 'Lithuania', emoji: '🇱🇹' },
  { code: 'LU', label: 'Luxembourg', emoji: '🇱🇺' },
  { code: 'MG', label: 'Madagascar', emoji: '🇲🇬' },
  { code: 'MW', label: 'Malawi', emoji: '🇲🇼' },
  { code: 'MY', label: 'Malaysia', emoji: '🇲🇾' },
  { code: 'MV', label: 'Maldives', emoji: '🇲🇻' },
  { code: 'ML', label: 'Mali', emoji: '🇲🇱' },
  { code: 'MT', label: 'Malta', emoji: '🇲🇹' },
  { code: 'MH', label: 'Marshall Islands', emoji: '🇲🇭' },
  { code: 'MR', label: 'Mauritania', emoji: '🇲🇷' },
  { code: 'MU', label: 'Mauritius', emoji: '🇲🇺' },
  { code: 'MX', label: 'Mexico', emoji: '🇲🇽' },
  { code: 'FM', label: 'Micronesia', emoji: '🇫🇲' },
  { code: 'MD', label: 'Moldova', emoji: '🇲🇩' },
  { code: 'MC', label: 'Monaco', emoji: '🇲🇨' },
  { code: 'MN', label: 'Mongolia', emoji: '🇲🇳' },
  { code: 'ME', label: 'Montenegro', emoji: '🇲🇪' },
  { code: 'MA', label: 'Morocco', emoji: '🇲🇦' },
  { code: 'MZ', label: 'Mozambique', emoji: '🇲🇿' },
  { code: 'MM', label: 'Myanmar', emoji: '🇲🇲' },
  { code: 'NA', label: 'Namibia', emoji: '🇳🇦' },
  { code: 'NR', label: 'Nauru', emoji: '🇳🇷' },
  { code: 'NP', label: 'Nepal', emoji: '🇳🇵' },
  { code: 'NL', label: 'Netherlands', emoji: '🇳🇱' },
  { code: 'NZ', label: 'New Zealand', emoji: '🇳🇿' },
  { code: 'NI', label: 'Nicaragua', emoji: '🇳🇮' },
  { code: 'NE', label: 'Niger', emoji: '🇳🇪' },
  { code: 'NG', label: 'Nigeria', emoji: '🇳🇬' },
  { code: 'MK', label: 'North Macedonia', emoji: '🇲🇰' },
  { code: 'NO', label: 'Norway', emoji: '🇳🇴' },
  { code: 'OM', label: 'Oman', emoji: '🇴🇲' },
  { code: 'PK', label: 'Pakistan', emoji: '🇵🇰' },
  { code: 'PW', label: 'Palau', emoji: '🇵🇼' },
  { code: 'PS', label: 'Palestine', emoji: '🇵🇸' },
  { code: 'PA', label: 'Panama', emoji: '🇵🇦' },
  { code: 'PG', label: 'Papua New Guinea', emoji: '🇵🇬' },
  { code: 'PY', label: 'Paraguay', emoji: '🇵🇾' },
  { code: 'PE', label: 'Peru', emoji: '🇵🇪' },
  { code: 'PH', label: 'Philippines', emoji: '🇵🇭' },
  { code: 'PL', label: 'Poland', emoji: '🇵🇱' },
  { code: 'PT', label: 'Portugal', emoji: '🇵🇹' },
  { code: 'QA', label: 'Qatar', emoji: '🇶🇦' },
  { code: 'RO', label: 'Romania', emoji: '🇷🇴' },
  { code: 'RU', label: 'Russia', emoji: '🇷🇺' },
  { code: 'RW', label: 'Rwanda', emoji: '🇷🇼' },
  { code: 'KN', label: 'Saint Kitts and Nevis', emoji: '🇰🇳' },
  { code: 'LC', label: 'Saint Lucia', emoji: '🇱🇨' },
  { code: 'VC', label: 'Saint Vincent and the Grenadines', emoji: '🇻🇨' },
  { code: 'WS', label: 'Samoa', emoji: '🇼🇸' },
  { code: 'SM', label: 'San Marino', emoji: '🇸🇲' },
  { code: 'ST', label: 'Sao Tome and Principe', emoji: '🇸🇹' },
  { code: 'SA', label: 'Saudi Arabia', emoji: '🇸🇦' },
  { code: 'SN', label: 'Senegal', emoji: '🇸🇳' },
  { code: 'RS', label: 'Serbia', emoji: '🇷🇸' },
  { code: 'SC', label: 'Seychelles', emoji: '🇸🇨' },
  { code: 'SL', label: 'Sierra Leone', emoji: '🇸🇱' },
  { code: 'SG', label: 'Singapore', emoji: '🇸🇬' },
  { code: 'SK', label: 'Slovakia', emoji: '🇸🇰' },
  { code: 'SI', label: 'Slovenia', emoji: '🇸🇮' },
  { code: 'SB', label: 'Solomon Islands', emoji: '🇸🇧' },
  { code: 'SO', label: 'Somalia', emoji: '🇸🇴' },
  { code: 'ZA', label: 'South Africa', emoji: '🇿🇦' },
  { code: 'SS', label: 'South Sudan', emoji: '🇸🇸' },
  { code: 'ES', label: 'Spain', emoji: '🇪🇸' },
  { code: 'LK', label: 'Sri Lanka', emoji: '🇱🇰' },
  { code: 'SD', label: 'Sudan', emoji: '🇸🇩' },
  { code: 'SR', label: 'Suriname', emoji: '🇸🇷' },
  { code: 'SE', label: 'Sweden', emoji: '🇸🇪' },
  { code: 'CH', label: 'Switzerland', emoji: '🇨🇭' },
  { code: 'SY', label: 'Syria', emoji: '🇸🇾' },
  { code: 'TW', label: 'Taiwan', emoji: '🇹🇼' },
  { code: 'TJ', label: 'Tajikistan', emoji: '🇹🇯' },
  { code: 'TZ', label: 'Tanzania', emoji: '🇹🇿' },
  { code: 'TH', label: 'Thailand', emoji: '🇹🇭' },
  { code: 'TL', label: 'Timor-Leste', emoji: '🇹🇱' },
  { code: 'TG', label: 'Togo', emoji: '🇹🇬' },
  { code: 'TO', label: 'Tonga', emoji: '🇹🇴' },
  { code: 'TT', label: 'Trinidad and Tobago', emoji: '🇹🇹' },
  { code: 'TN', label: 'Tunisia', emoji: '🇹🇳' },
  { code: 'TR', label: 'Turkey', emoji: '🇹🇷' },
  { code: 'TM', label: 'Turkmenistan', emoji: '🇹🇲' },
  { code: 'TV', label: 'Tuvalu', emoji: '🇹🇻' },
  { code: 'UG', label: 'Uganda', emoji: '🇺🇬' },
  { code: 'UA', label: 'Ukraine', emoji: '🇺🇦' },
  { code: 'AE', label: 'United Arab Emirates', emoji: '🇦🇪' },
  { code: 'GB', label: 'United Kingdom', emoji: '🇬🇧' },
  { code: 'US', label: 'United States', emoji: '🇺🇸' },
  { code: 'UY', label: 'Uruguay', emoji: '🇺🇾' },
  { code: 'UZ', label: 'Uzbekistan', emoji: '🇺🇿' },
  { code: 'VU', label: 'Vanuatu', emoji: '🇻🇺' },
  { code: 'VE', label: 'Venezuela', emoji: '🇻🇪' },
  { code: 'VN', label: 'Vietnam', emoji: '🇻🇳' },
  { code: 'YE', label: 'Yemen', emoji: '🇾🇪' },
  { code: 'ZM', label: 'Zambia', emoji: '🇿🇲' },
  { code: 'ZW', label: 'Zimbabwe', emoji: '🇿🇼' },
];

/**
 * Returns a high-quality SVG flag URL for a given ISO 3166-1 alpha-2 country code.
 * Uses flagcdn.com for consistent rendering across all platforms (especially Windows).
 * 
 * @param {string} code - The ISO country code (e.g., 'US', 'GB')
 * @returns {string} The URL to the SVG flag image
 */
export const getFlagUrl = (code) => {
  if (!code) return '';
  return `https://flagcdn.com/${code.toLowerCase()}.svg`;
};
